### PR TITLE
Disable auto popup of Output window

### LINKED ISSUE #2: Output window comes into foreground whenever anything bad happens
Any errors that are coming through the Ember Language Server cause the Output window to switch to `Ember Language Server` and come into the foreground. This is a bit overzealous as even writing out the name of a component causes an error for each letter typed until the name is correct.

_I tried to record a gif but LICEcap recorded black for some reason_

For example: 

```hbs
{{!--templates/application.hbs--}}
Hello World
```

All is well, no errors are present. Begin adding a component into my template:

```hbs
{{!--templates/application.hbs--}}
Hello World
{{my-co
```

An error is logged for each input letter:
```Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
  Code: -32603 
[Error - 11:22:06 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Parse error on line 2:
Hello World{{mELSCompletionDummy
-------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
  Code: -32603 
[Error - 11:22:07 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Parse error on line 2:
Hello World{{myELSCompletionDummy
-------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
  Code: -32603 
[Error - 11:22:07 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Parse error on line 2:
Hello World{{my-ELSCompletionDumm
-------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
  Code: -32603 
[Error - 11:22:08 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Parse error on line 2:
Hello World{{my-cELSCompletionDum
-------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
  Code: -32603 
[Error - 11:22:08 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Parse error on line 2:
Hello World{{my-coELSCompletionDu
-------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
  Code: -32603 
```

Until the component name is valid:
```hbs
{{!--templates/application.hbs--}}
Hello World
{{my-component}}
```

Each error causing the Output window to appear, which is very annoying.

### PR DESCRIPTION
**Pull request by dwatts1772**
Resolves #2

### CODE REVIEW

**Comment by t-sauer** [comment]
Thank you very much. Will probably publish it later tonight.

**Comment by dwatts1772** [comment]
No problem at all! Really just want that Output window gone! haha.  I look forward to the publish

**Comment by dwatts1772** [comment]
@t-sauer Any update on when you're going to be able to publish the update?  Thanks again

**Comment by t-sauer** [comment]
Completely forgot about it, sorry. Will try to do it as fast as possible.

**Comment by dwatts1772** [comment]
No worries! Thanks again!

**Comment by t-sauer** [comment]
I just published version 0.1.1

**Pull request merged**
